---
title: "Visualizing Fantasy Playoff Odds"
output: html_notebook
---

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(reshape2)
library(ggalluvial)
library(forcats)
library(readxl)
library(ggrepel)
library(viridis)
library(hrbrthemes)
```

```{r}
weekly_chart <- read.csv("weekly_chart.csv") #from ipynb script

weekly_chart
```

```{r}
tmp <- weekly_chart %>%
  mutate(team2=team)
tmp$team <- factor(tmp$team, c("Leading the League in USACs","The Teamwork Encouragers","GhostOfRayLewis","Chase\'s Superb Team","5 and Juan","N888888888888888888","CTE Pros (not concussions-SQL)","ACE of L.A.D.","Fool Me 100 Times Shame On Me","The Dream Team","#CorruptCommish","Rod the Great\'s Team","Chip Kelly","Erik\'s Peerless Team")) #replace with code from bottom of ipynb for best ordering on final product


tmp %>%
  ggplot( aes(x=week, y=Playoffs)) +
    geom_line( data=tmp %>% dplyr::select(-team), aes(group=team2), color="grey", size=0.5, alpha=0.5) +
    geom_line( aes(color=team), color="#69b3a2", size=1.2 )+
    scale_color_viridis(discrete = TRUE) +
    scale_x_continuous(breaks=seq(0,3,by=1)) +
    theme_ipsum() +
    theme(
      legend.position="none",
      plot.title = element_text(size=14),
      panel.grid = element_blank()
    ) +
    ggtitle("City of Flight, Playoff Probs Through Week 20") +
    facet_wrap(~team)

ggsave(file="cof_wk20_playoffs.jpeg", width=14, height=14, dpi=400)
```

